### ISSUE TITLE
Running command from outside scripts folder fails

### ISSUE THREAD

**Issue by siewers** [BorisWilhelms/create-dotnet-devcert#9]
First of all, awesome job!

When I'm running the command `./scripts//ubuntu-create-dotnet-devcert.sh`, as written in the readme, I receive the error:
```
./scripts/ubuntu-create-dotnet-devcert.sh: 2: .: Can't open ./common.sh
```

However, when I run the command from the scripts folder, everything works as expected.

It would be nice to be able to invoke the command from any location.

**Comment by BorisWilhelms** [comment]
Thanks for the feedback. This is fixed now.
